# Generated by Django 3.1.2 on 2020-10-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=30, unique=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
